// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: navigation.yaml

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../wrappers/add_task_sheet_wrapper.dart';
import '../wrappers/home_page_wrapper.dart';

/// The route table declared in navigation.yaml.
///
/// How a destination appears is a property of the route, so the page a route
/// builds is what decides whether it arrives as a screen, a bottom sheet or a
/// dialog. Everything is pushed and popped the same way, and a behavior never
/// has to say which kind it is.
///
/// The observers are for the suite: a generated test passes a recorder and
/// verifies the pushes a scenario says the app makes.
GoRouter buildRouter({List<NavigatorObserver> observers = const []}) {
  return GoRouter(
    initialLocation: '/home',
    observers: observers,
    routes: <RouteBase>[
      GoRoute(
        name: 'addTask',
        path: '/add_task',
        pageBuilder: (context, state) => ModalBottomSheetPage<void>(
          key: state.pageKey,
          name: 'addTask',
          child: const AddTaskSheetWrapper(),
        ),
      ),
      GoRoute(
        name: 'home',
        path: '/home',
        pageBuilder: (context, state) => MaterialPage<void>(
          key: state.pageKey,
          name: 'home',
          child: const HomePageWrapper(),
        ),
      ),
    ],
  );
}

/// A route that shows its child in a modal bottom sheet.
///
/// go_router builds pages, and a sheet is a route like any other, so this is
/// the page whose route is the one showModalBottomSheet would have pushed. The
/// sheet is built below the Navigator, which is below whatever provides the
/// stores, so a widget inside it reads them exactly as a page does.
class ModalBottomSheetPage<T> extends Page<T> {
  const ModalBottomSheetPage({required this.child, super.key, super.name});

  final Widget child;

  @override
  Route<T> createRoute(BuildContext context) {
    final theme = Theme.of(context).bottomSheetTheme;
    return ModalBottomSheetRoute<T>(
      settings: this,
      // Scroll controlled, which is the only setting that lets a sheet be as
      // tall as its content. The alternative caps it at nine sixteenths of the
      // screen, and a Column fills whatever it is given, so every sheet came
      // out the same height whatever was in it.
      isScrollControlled: true,
      // Which is why the top of a tall sheet has to stop somewhere.
      useSafeArea: true,
      constraints: theme.constraints,
      modalBarrierColor: theme.modalBarrierColor,
      barrierLabel: MaterialLocalizations.of(context).modalBarrierDismissLabel,
      builder: (context) => Padding(
        // A keyboard pushes the sheet up rather than covering it, which is
        // what a sheet holding a text field needs and what nothing else in
        // the tree is in a position to do.
        padding: EdgeInsets.only(
          bottom: MediaQuery.of(context).viewInsets.bottom,
        ),
        child: SingleChildScrollView(
          // The scroll view is what makes the height come from the content:
          // it offers an unbounded height, so the child sizes to itself and
          // scrolls only once it is taller than the screen.
          //
          // The width is the other half of the same point. A sheet spans what
          // it is given, and a Column shrink-wraps, so without this the widget
          // would have to know it is in a sheet to look right in one.
          child: SizedBox(width: double.infinity, child: child),
        ),
      ),
    );
  }
}

