package dart

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Marker is the first line of every file this engine generates. Pruning uses it
// to tell its own output from anything a person put in the same directory.
const Marker = "GENERATED BY METACODE"

// StubMarker follows Marker in a file the deterministic stages wrote and no
// model has touched yet. It is the engine's answer to "has this file ever been
// implemented", asked of the file itself rather than of any record kept beside
// it: a deleted lib/stores/, a fresh clone, a hand-reverted body. A spec diff
// cannot see any of those, and the freeze set needs all of them.
//
// It is a suffix of Marker's line rather than a marker of its own, so pruning
// keeps matching both forms with one string.
const StubMarker = "SCAFFOLDING ONLY"

// StubHeader is the first line of a file the scaffold wrote and a model has
// not. Generators that render their own header write this one.
const StubHeader = "// " + Marker + " - " + StubMarker

// ImplementedHeader is the first line of a file a model has written.
const ImplementedHeader = "// " + Marker + " - DO NOT EDIT BY HAND"

// IsStub reports whether the file at path is generated output that no model
// has written yet. A file that is absent or unreadable is not a stub: there is
// nothing there to preserve, so the caller writes it.
func IsStub(path string) bool {
	header, ok := readHeader(path)
	return ok && strings.Contains(header, Marker) && strings.Contains(header, StubMarker)
}

// IsImplemented reports whether the file at path is generated output a model
// has already written. Those are the files a scaffold step must not overwrite.
func IsImplemented(path string) bool {
	header, ok := readHeader(path)
	return ok && strings.Contains(header, Marker) && !strings.Contains(header, StubMarker)
}

func readHeader(path string) (string, bool) {
	f, err := os.Open(path)
	if err != nil {
		return "", false
	}
	defer f.Close()

	buf := make([]byte, markerScanLimit)
	n, err := f.Read(buf)
	if err != nil && n == 0 {
		return "", false
	}
	return string(buf[:n]), true
}

// markerScanLimit is how far into a file the marker is looked for. It sits in
// the header comment, so a short prefix is enough.
const markerScanLimit = 512

// Prune deletes generated files under the given directories that the current
// run did not produce. Paths in expected are relative to root, slash-separated.
//
// A file is removed only if it carries Marker, so hand-written files in the same
// directory survive. The engine owns lib/ and test/ end to end, so a marked
// file whose spec source is gone is output nothing will regenerate.
func Prune(root string, dirs []string, expected map[string]bool) ([]string, error) {
	var removed []string

	for _, dir := range dirs {
		abs := filepath.Join(root, filepath.FromSlash(dir))
		entries, err := os.ReadDir(abs)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read %s: %w", dir, err)
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			rel := dir + "/" + entry.Name()
			if expected[rel] {
				continue
			}
			path := filepath.Join(abs, entry.Name())
			generated, err := isGenerated(path)
			if err != nil {
				return nil, err
			}
			if !generated {
				continue
			}
			if err := os.Remove(path); err != nil {
				return nil, fmt.Errorf("remove %s: %w", rel, err)
			}
			removed = append(removed, rel)
		}
	}

	sort.Strings(removed)
	return removed, nil
}

// isGenerated reports whether pruning owns this file. An empty or unreadable
// file is not something this engine wrote, so readHeader failing is a no.
func isGenerated(path string) (bool, error) {
	header, ok := readHeader(path)
	return ok && strings.Contains(header, Marker), nil
}
