// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/task_cubit.dart';
import '../widgets/add_task_sheet.dart';
import '../wrappers/cancel_button_wrapper.dart';
import '../wrappers/save_task_button_wrapper.dart';

class AddTaskSheetWrapper extends StatelessWidget {
  const AddTaskSheetWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return AddTaskSheet(
      cancelButton: const CancelButtonWrapper(),
      saveTaskButton: const SaveTaskButtonWrapper(),
    );
  }
}