// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import '../stores/task_cubit.dart';
import '../widgets/cancel_button.dart';

class CancelButtonWrapper extends StatelessWidget {
  const CancelButtonWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return CancelButton(
      onCancel: () => context.pop(),
    );
  }
}