// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/task_cubit.dart';
import '../stores/task_state.dart';
import '../widgets/default_state.dart';
import '../widgets/empty_state.dart';
import '../wrappers/task_tile_wrapper.dart';

class DefaultStateWrapper extends StatelessWidget {
  const DefaultStateWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TaskCubit, TaskState>(
      builder: (context, state) {
        if (state.value.isEmpty) {
          return const EmptyState();
        }
        return DefaultState(
          taskList: state.value,
          taskTile: (context, index) => TaskTileWrapper(index: index),
        );
      },
    );
  }
}