// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../pages/home_page.dart';
import '../stores/task_cubit.dart';
import '../wrappers/add_task_button_wrapper.dart';
import '../wrappers/default_state_wrapper.dart';

class HomePageWrapper extends StatelessWidget {
  const HomePageWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return HomePage(
      homeContent: const DefaultStateWrapper(),
      addTaskButton: const AddTaskButtonWrapper(),
    );
  }
}