// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import '../stores/task_cubit.dart';
import '../widgets/save_task_button.dart';

class SaveTaskButtonWrapper extends StatelessWidget {
  const SaveTaskButtonWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return SaveTaskButton(
      onSaveTask: () {
        context.read<TaskCubit>().saveTask();
        context.pop();
      },
    );
  }
}