// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/task_cubit.dart';
import '../widgets/task_checkbox.dart';

class TaskCheckboxWrapper extends StatelessWidget {
  const TaskCheckboxWrapper({super.key, required this.index});
  final int index;

  @override
  Widget build(BuildContext context) {
    final done =
        context.select((TaskCubit cubit) => cubit.state.value[index].done);
    return TaskCheckbox(
      index: index,
      taskToggled: (_) => context.read<TaskCubit>().taskToggled(index),
      taskDone: done,
    );
  }
}