package flutter

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/pietroid/metacode/engine/internal/core/ir"
	"github.com/pietroid/metacode/engine/internal/modules/data"
	"github.com/pietroid/metacode/engine/internal/modules/shared"
	"github.com/pietroid/metacode/engine/internal/modules/ui/catalog"
	"github.com/pietroid/metacode/engine/internal/planner"
)

// GenerateDeterministicWrappers generates wiring wrappers without using an LLM.
// It handles the common counter-app patterns (variable display via BlocSelector
// and button events that call a Cubit action) and updates lib/app.dart.
func GenerateDeterministicWrappers(app *ir.IR, tasks []planner.Task, outDir string) error {
	if len(app.Stores) == 0 {
		return nil
	}

	wrappersDir := filepath.Join(outDir, "lib", "wrappers")
	if err := os.MkdirAll(wrappersDir, 0755); err != nil {
		return fmt.Errorf("create wrappers dir: %w", err)
	}

	byWidget := make(map[string][]planner.Task)
	for _, task := range tasks {
		if task.Type != planner.TaskWrapper {
			continue
		}
		widgetName := widgetNameForWrapperTask(task, app)
		if widgetName == "" {
			continue
		}
		byWidget[widgetName] = append(byWidget[widgetName], task)
	}
	if len(byWidget) == 0 {
		return nil
	}

	store := app.Stores[0]
	generated := make(map[string]string) // target file -> wrapper class name
	c := catalog.New()

	allChildWrappers := childWrapperClasses(app, tasks)

	for widgetName, widgetTasks := range byWidget {
		comp := shared.FindComponent(app.UI, widgetName)
		if comp == nil {
			continue
		}

		className := wrapperClassName(widgetName)
		fileName := shared.SnakeCase(widgetName) + "_wrapper.dart"
		targetFile := filepath.Join("lib", "wrappers", fileName)

		var code string
		var err error
		switch {
		case shared.IsPageName(widgetName):
			code, err = generatePageWrapper(widgetName, *comp, app, widgetTasks, allChildWrappers, store, c)
		case isButtonKind(comp.Kind):
			code, err = generateButtonWrapper(*comp, app, widgetTasks, store, c)
		default:
			code, err = generateFallbackWrapper(*comp, app, store, c)
		}
		if err != nil {
			return fmt.Errorf("wrapper %s: %w", widgetName, err)
		}

		path := filepath.Join(outDir, targetFile)
		if err := os.WriteFile(path, []byte(code), 0644); err != nil {
			return fmt.Errorf("write wrapper %s: %w", path, err)
		}
		generated[targetFile] = className
	}

	if len(generated) > 0 {
		if err := updateAppDart(app, outDir, generated); err != nil {
			return fmt.Errorf("update app.dart: %w", err)
		}
	}

	return nil
}

func widgetNameForWrapperTask(task planner.Task, app *ir.IR) string {
	scenario, err := findScenario(app, task.ScenarioID)
	if err != nil {
		// Fallback to task ID: wrapper-<widget>-<member>
		parts := strings.Split(task.ID, "-")
		if len(parts) >= 2 {
			return shared.PascalCase(strings.Join(parts[1:len(parts)-1], "_"))
		}
		return ""
	}
	if w, _, ok := splitWidgetRef(app, scenario.Then.Target); ok {
		return w
	}
	if w, _, ok := splitWidgetRef(app, scenario.When); ok {
		return w
	}
	return ""
}

func isButtonKind(kind string) bool {
	switch kind {
	case "elevatedButton", "textButton", "iconButton", "floatingActionButton":
		return true
	}
	return false
}

func generatePageWrapper(pageName string, comp ir.UIComponent, app *ir.IR, tasks []planner.Task, childWrappers map[string]string, store ir.Store, c *catalog.Catalog) (string, error) {
	base := shared.StoreBaseName(store.Name)
	bindings := inferVariableBindings(app, pageName, store)

	title := ""
	if appBarRaw, ok := comp.Props["appBar"].(map[string]any); ok {
		if t, ok := appBarRaw["title"].(string); ok {
			title = t
		}
	}

	var bodyChildren []string
	bodyRaw, ok := comp.Props["body"].(map[string]any)
	if ok {
		centerRaw, ok := bodyRaw["center"].(map[string]any)
		if ok {
			if columnList, ok := centerRaw["column"].([]any); ok {
				for _, item := range columnList {
					bodyChildren = append(bodyChildren, renderWrapperListItem(item, app, c, bindings, childWrappers, store))
				}
			}
		}
	}

	childrenArg := ""
	if len(bodyChildren) > 0 {
		childrenArg = fmt.Sprintf("children: [\n%s\n          ]", shared.Indent(strings.Join(bodyChildren, ",\n")))
	}

	var imports []string
	imports = append(imports,
		"import 'package:flutter/material.dart';",
		"import 'package:flutter_bloc/flutter_bloc.dart';",
		fmt.Sprintf("import '../stores/%s_cubit.dart';", shared.SnakeCase(base)),
		fmt.Sprintf("import '../stores/%s_state.dart';", shared.SnakeCase(base)),
	)
	for childName := range childWrappers {
		imports = append(imports, fmt.Sprintf("import '%s_wrapper.dart';", shared.SnakeCase(childName)))
	}

	className := wrapperClassName(pageName)
	return fmt.Sprintf(`// GENERATED BY METACODE - DO NOT EDIT BY HAND
%s

class %s extends StatelessWidget {
  const %s({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text(%s)),
      body: Center(
        child: Column(
          %s,
        ),
      ),
    );
  }
}
`, strings.Join(imports, "\n"), className, className, shared.DartStringLiteral(title), childrenArg), nil
}

func generateButtonWrapper(comp ir.UIComponent, app *ir.IR, tasks []planner.Task, store ir.Store, c *catalog.Catalog) (string, error) {
	base := shared.StoreBaseName(store.Name)
	cubitClass := shared.PascalCase(base) + "Cubit"

	method := inferButtonAction(comp.Name, app, store)

	sym, ok := c.Find(comp.Kind)
	if !ok {
		return "", fmt.Errorf("unknown button kind %q", comp.Kind)
	}

	child := "const SizedBox()"
	if val, ok := comp.Props[catalog.PropChild]; ok {
		child = renderWrapperPropValue(val, true, app, c, nil, nil, store)
	}

	return fmt.Sprintf(`// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/%s_cubit.dart';

class %s extends StatelessWidget {
  const %s({super.key});

  @override
  Widget build(BuildContext context) {
    return %s(
      onPressed: () => context.read<%s>().%s(),
      child: %s,
    );
  }
}
`, shared.SnakeCase(base),
		wrapperClassName(comp.Name), wrapperClassName(comp.Name),
		sym.FlutterWidget, cubitClass, method, child), nil
}

func generateFallbackWrapper(comp ir.UIComponent, app *ir.IR, store ir.Store, c *catalog.Catalog) (string, error) {
	className := wrapperClassName(comp.Name)
	return fmt.Sprintf(`// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';

class %s extends StatelessWidget {
  const %s({super.key});

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
`, className, className), nil
}

func renderWrapperListItem(raw any, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	switch v := raw.(type) {
	case string:
		if wrapperClass, ok := childWrappers[v]; ok {
			return wrapperClass + "()"
		}
		if sym, ok := app.Symbols.Lookup(v); ok && sym.Kind == "widget" {
			return fmt.Sprintf("const %s()", shared.PascalCase(v))
		}
		return fmt.Sprintf("const Text(%s)", shared.DartStringLiteral(v))
	case map[string]any:
		if len(v) == 1 {
			for k, val := range v {
				if k == "text" {
					if s, ok := val.(string); ok {
						if expr, ok := bindings[s]; ok {
							base := shared.StoreBaseName(store.Name)
							cubitClass := shared.PascalCase(base) + "Cubit"
							stateClass := shared.PascalCase(base) + "State"
							return fmt.Sprintf("BlocSelector<%s, %s, String>(\n  selector: (state) => %s,\n  builder: (context, %s) => Text(%s),\n)", cubitClass, stateClass, expr, s, s)
						}
						return fmt.Sprintf("const Text(%s)", shared.DartStringLiteral(s))
					}
				}
				if c.IsKnown(k) {
					comp := rawMapToComponent(v, k, c)
					return renderWrapperComponent(comp, app, c, bindings, childWrappers, store)
				}
				if wrapperClass, ok := childWrappers[k]; ok {
					return wrapperClass + "()"
				}
				return fmt.Sprintf("const %s()", shared.PascalCase(k))
			}
		}
	}
	return "const SizedBox()"
}

func renderWrapperComponent(comp ir.UIComponent, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	if sym, ok := c.Find(comp.Kind); ok {
		return renderWrapperCatalogWidget(comp, sym, app, c, bindings, childWrappers, store)
	}
	if wrapperClass, ok := childWrappers[comp.Name]; ok {
		return wrapperClass + "()"
	}
	return fmt.Sprintf("const %s()", shared.PascalCase(comp.Name))
}

func renderWrapperCatalogWidget(comp ir.UIComponent, sym catalog.Symbol, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	var args []string
	if sym.DefaultProp != "" {
		if arg := renderWrapperDefaultProp(comp, sym, app, c, bindings, childWrappers, store); arg != "" {
			args = append(args, arg)
		}
	}
	for prop, val := range comp.Props {
		if prop == sym.DefaultProp {
			continue
		}
		expectsWidget := c.WidgetProp(comp.Kind, prop)
		args = append(args, fmt.Sprintf("%s: %s", prop, renderWrapperPropValue(val, expectsWidget, app, c, bindings, childWrappers, store)))
	}
	if len(args) == 0 {
		return sym.FlutterWidget + "()"
	}
	return fmt.Sprintf("%s(\n%s\n)", sym.FlutterWidget, shared.Indent(strings.Join(args, ",\n")))
}

func renderWrapperDefaultProp(comp ir.UIComponent, sym catalog.Symbol, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	prop := sym.DefaultProp
	switch prop {
	case catalog.PropChild:
		if len(comp.Children) > 0 {
			return fmt.Sprintf("child: %s", renderWrapperComponent(comp.Children[0], app, c, bindings, childWrappers, store))
		}
		if val, ok := comp.Props[prop]; ok {
			return fmt.Sprintf("child: %s", renderWrapperPropValue(val, true, app, c, bindings, childWrappers, store))
		}
	case catalog.PropChildren:
		if len(comp.Children) > 0 {
			return fmt.Sprintf("children: %s", renderWrapperChildrenList(comp.Children, app, c, bindings, childWrappers, store))
		}
		if list, ok := comp.Props[prop].([]any); ok {
			return fmt.Sprintf("children: %s", renderWrapperRawList(list, true, app, c, bindings, childWrappers, store))
		}
	case catalog.PropTitle, catalog.PropData:
		if val, ok := comp.Props[prop].(string); ok {
			if prop == catalog.PropData {
				if _, bound := bindings[val]; bound {
					return ""
				}
			}
			return fmt.Sprintf("%s: const Text(%s)", prop, shared.DartStringLiteral(val))
		}
	default:
		if val, ok := comp.Props[prop]; ok {
			return fmt.Sprintf("%s: %s", prop, renderWrapperPropValue(val, false, app, c, bindings, childWrappers, store))
		}
	}
	return ""
}

func renderWrapperPropValue(val any, expectsWidget bool, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	switch v := val.(type) {
	case string:
		if expectsWidget {
			if shared.IsVariableIdentifier(v) && !c.IsKnown(v) {
				return fmt.Sprintf("Text(%s)", v)
			}
			return fmt.Sprintf("const Text(%s)", shared.DartStringLiteral(v))
		}
		if shared.IsVariableIdentifier(v) && !c.IsKnown(v) {
			return v
		}
		return shared.DartStringLiteral(v)
	case map[string]any:
		if expectsWidget {
			comp := rawMapToComponent(v, "", c)
			return renderWrapperComponent(comp, app, c, bindings, childWrappers, store)
		}
		return "Container()"
	case []any:
		return renderWrapperRawList(v, expectsWidget, app, c, bindings, childWrappers, store)
	default:
		return fmt.Sprintf("%v", v)
	}
}

func renderWrapperRawList(list []any, expectsWidget bool, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	var parts []string
	for _, item := range list {
		parts = append(parts, renderWrapperListItem(item, app, c, bindings, childWrappers, store))
	}
	return fmt.Sprintf("[\n%s\n]", shared.Indent(strings.Join(parts, ",\n")))
}

func renderWrapperChildrenList(children []ir.UIComponent, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	var parts []string
	for _, child := range children {
		parts = append(parts, renderWrapperComponent(child, app, c, bindings, childWrappers, store))
	}
	return fmt.Sprintf("[\n%s\n]", shared.Indent(strings.Join(parts, ",\n")))
}

func rawMapToComponent(m map[string]any, parentName string, c *catalog.Catalog) ir.UIComponent {
	if len(m) == 1 {
		for k, val := range m {
			if c.IsKnown(k) {
				comp := buildWrapperComponentValue(val, k, c)
				comp.Name = k
				comp.Kind = k
				return comp
			}
			return ir.UIComponent{Name: k, Kind: "widget"}
		}
	}
	return ir.UIComponent{Name: parentName, Kind: parentName, Props: m}
}

func buildWrapperComponentValue(raw any, name string, c *catalog.Catalog) ir.UIComponent {
	comp := ir.UIComponent{Name: name, Kind: name, Props: make(map[string]any)}
	switch v := raw.(type) {
	case map[string]any:
		comp.Props = v
	case string:
		if sym, ok := c.Find(name); ok {
			comp.Props[sym.DefaultProp] = v
		}
	case []any:
		if sym, ok := c.Find(name); ok && sym.DefaultProp == catalog.PropChildren {
			comp.Props[sym.DefaultProp] = v
		}
	}
	return comp
}

func childWrapperClasses(app *ir.IR, tasks []planner.Task) map[string]string {
	out := make(map[string]string)
	for _, task := range tasks {
		if task.Type != planner.TaskWrapper {
			continue
		}
		childName := widgetNameForWrapperTask(task, app)
		if childName == "" || shared.IsPageName(childName) {
			continue
		}
		out[childName] = wrapperClassName(childName)
	}
	return out
}

func inferVariableBindings(app *ir.IR, pageName string, store ir.Store) map[string]string {
	bindings := make(map[string]string)
	storeNames := map[string]bool{store.Name: true, shared.StoreBaseName(store.Name): true}
	for _, b := range app.Behaviors {
		if b.Then == nil || b.Given == nil {
			continue
		}
		if !strings.HasPrefix(b.Then.Target, pageName+".") {
			continue
		}
		varName := strings.TrimPrefix(b.Then.Target, pageName+".")
		root, field := data.SplitDot(b.Given.Target)
		if !storeNames[root] || field == "" {
			continue
		}
		if b.Then.Value == b.Given.Value {
			bindings[varName] = fmt.Sprintf("state.%s.toString()", field)
		}
	}
	return bindings
}

func inferButtonAction(widgetName string, app *ir.IR, store ir.Store) string {
	prefix := widgetName + ".onPressed"
	for _, b := range app.Behaviors {
		if b.When == "" || !strings.HasPrefix(b.When, prefix) {
			continue
		}
		if b.Then == nil {
			continue
		}
		root, _ := data.SplitDot(b.Then.Target)
		if root != store.Name && root != shared.StoreBaseName(store.Name) {
			continue
		}
		given := 0
		if b.Given != nil {
			if v, err := strconv.Atoi(b.Given.Value); err == nil {
				given = v
			}
		}
		then := 0
		if v, err := strconv.Atoi(b.Then.Value); err == nil {
			then = v
		}
		if then > given {
			return "increment"
		}
		if then < given {
			return "decrement"
		}
	}
	return "increment"
}
