// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: data.yaml > counterStore

import 'package:flutter_bloc/flutter_bloc.dart';
import 'counter_state.dart';

class CounterCubit extends Cubit<CounterState> {
  CounterCubit() : super(const CounterState(value: 0));

  void increment() => emit(state.copyWith(value: state.value + 1));

}
