// GENERATED BY METACODE - SCAFFOLDING ONLY
// Source spec: data.yaml > counterStore
//
// The class, its state, and the method signatures come from the specs. Method
// bodies are business logic: they are filled in from the behavior scenarios by
// the fix loop, and re-scaffolded on the next run.

import 'package:flutter_bloc/flutter_bloc.dart';
import 'counter_state.dart';

class CounterCubit extends Cubit<CounterState> {
  CounterCubit() : super(const CounterState(value: 0));

  /// Specified by:
  ///   decrements from 1: given counterStore.value is 1, then counterStore.value should be 0
  ///   decrements from 2: given counterStore.value is 2, then counterStore.value should be 1
  ///   not decrements when is 0: given counterStore.value is 0, then counterStore.value should be 0
  void decrement() {
    // The counter is clamped at zero: decrementing from 0 must leave it at 0.
    final current = state.value;
    final next = current > 0 ? current - 1 : 0;
    emit(CounterState(value: next));
  }

  /// Specified by:
  ///   increments from 0: given counterStore.value is 0, then counterStore.value should be 1
  ///   increments from 1: given counterStore.value is 1, then counterStore.value should be 2
  ///   increments from 2: given counterStore.value is 2, then counterStore.value should be 3
  void increment() {
    emit(CounterState(value: state.value + 1));
  }
}