// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: data.yaml > taskStore
//
// The class, its state, and the method signatures come from the specs. Method
// bodies are business logic: they are filled in from the behavior scenarios by
// the implement stage. Once they are, the header above says DO NOT EDIT BY
// HAND and no later run re-scaffolds this file.

import 'package:flutter_bloc/flutter_bloc.dart';
import 'task_state.dart';
import '../models/task.dart';

class TaskCubit extends Cubit<TaskState> {
  TaskCubit() : super(const TaskState(value: []));

  /// Starts from a state a caller chooses, which is how a generated test sets
  /// up a scenario's "Given" without reaching into the store.
  TaskCubit.seeded(TaskState initial) : super(initial);

  /// Specified by:
  ///   adding/saving appends the task to the list: given taskStore.value: [], then taskStore.value.first.description should be New task
  void saveTask() {
    final newTask = Task(description: 'New task', done: false);
    emit(state.copyWith(value: [...state.value, newTask]));
  }

  /// Specified by:
  ///   toggling/toggling a row marks its task done: given taskStore.value: [{"description":"Buy milk","done":false}], then taskStore.value.first.done should be true
  void taskToggled(int index) {
    final tasks = List<Task>.from(state.value);
    final task = tasks[index];
    tasks[index] = Task(description: task.description, done: !task.done);
    emit(state.copyWith(value: tasks));
  }

}