// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: data.yaml > taskStore

import 'package:equatable/equatable.dart';
import '../models/task.dart';

class TaskState extends Equatable {
  const TaskState({required this.value});

  final List<Task> value;

  TaskState copyWith({List<Task>? value}) {
    return TaskState(value: value ?? this.value);
  }

  @override
  List<Object?> get props => [value];
}
