// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: models.yaml > task

import 'package:equatable/equatable.dart';

class Task extends Equatable {
  const Task({this.date, required this.description, required this.done, this.duration});
  final DateTime? date;
  final String description;
  final bool done;
  final num? duration;

  Task copyWith({DateTime? date, String? description, bool? done, num? duration}) {
    return Task(
      date: date ?? this.date,
      description: description ?? this.description,
      done: done ?? this.done,
      duration: duration ?? this.duration,
    );
  }

  @override
  List<Object?> get props => [date, description, done, duration];
}
