// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: navigation.yaml

import 'package:flutter/widgets.dart';

/// Records the routes a test pushed and popped.
///
/// An action leaves no state behind, so a scenario about one is verified
/// rather than expected: the test reads back the calls the app made. Flutter
/// already ships the seam for navigation, which is why nothing in lib/ knows
/// this class exists.
///
/// The name of each entry is the route name from navigation.yaml, carried on
/// the page the router built.
class NavigationSpy extends NavigatorObserver {
  final List<String> pushed = <String>[];
  final List<String> popped = <String>[];

  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) {
    pushed.add(route.settings.name ?? '');
  }

  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) {
    popped.add(route.settings.name ?? '');
  }

  /// Forgets everything recorded so far, which is how a test separates the
  /// navigation its `given` performed from the navigation the scenario is
  /// about.
  void clear() {
    pushed.clear();
    popped.clear();
  }
}
