// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/task_cubit.dart';
import '../widgets/add_task_button.dart';

class AddTaskButtonWrapper extends StatelessWidget {
  const AddTaskButtonWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return AddTaskButton(
      onAddTask: () => context.read<TaskCubit>().addTask(),
    );
  }
}