// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../models/task.dart';
import '../stores/task_cubit.dart';
import '../stores/task_state.dart';
import '../widgets/default_state.dart';
import '../wrappers/task_tile_wrapper.dart';

class DefaultStateWrapper extends StatelessWidget {
  const DefaultStateWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocSelector<TaskCubit, TaskState, List<Task>>(
      selector: (state) => state.value,
      builder: (context, tasks) => DefaultState(
        taskList: tasks,
        taskTile: (context, index) => TaskTileWrapper(index: index),
      ),
    );
  }
}