// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/task_cubit.dart';
import '../stores/task_state.dart';
import '../widgets/task_tile.dart';
import '../wrappers/task_checkbox_wrapper.dart';

class TaskTileWrapper extends StatelessWidget {
  const TaskTileWrapper({super.key, required this.index});
  final int index;

  @override
  Widget build(BuildContext context) {
    return BlocSelector<TaskCubit, TaskState, String>(
      selector: (state) => state.value[index].description,
      builder: (context, title) {
        return TaskTile(
          index: index,
          taskTitle: title,
          taskCheckbox: TaskCheckboxWrapper(index: index),
        );
      },
    );
  }
}