// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > addTaskSheet

import 'package:flutter/material.dart';

class AddTaskSheet extends StatelessWidget {
  const AddTaskSheet({super.key, required this.cancelButton, required this.saveTaskButton});
  final Widget cancelButton;
  final Widget saveTaskButton;

  @override
  Widget build(BuildContext context) {
    return Column(
    key: const Key('addTaskSheet'),
    children: [
        Text('New task'),
        saveTaskButton,
        cancelButton
    ]
);
  }
}
