// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > addTaskButton

import 'package:flutter/material.dart';

class AddTaskButton extends StatelessWidget {
  const AddTaskButton({super.key, this.onAddTask});
  final VoidCallback? onAddTask;

  @override
  Widget build(BuildContext context) {
    return FloatingActionButton(
    key: const Key('addTaskButton'),
    child: Icon(Icons.add),
    onPressed: onAddTask
);
  }
}
