// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > cancelButton

import 'package:flutter/material.dart';

class CancelButton extends StatelessWidget {
  const CancelButton({super.key, this.onCancel});
  final VoidCallback? onCancel;

  @override
  Widget build(BuildContext context) {
    return TextButton(
    key: const Key('cancelButton'),
    child: const Text('Cancel'),
    onPressed: onCancel
);
  }
}
