// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > saveTaskButton

import 'package:flutter/material.dart';

class SaveTaskButton extends StatelessWidget {
  const SaveTaskButton({super.key, this.onSaveTask});
  final VoidCallback? onSaveTask;

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
    key: const Key('saveTaskButton'),
    child: const Text('Save'),
    onPressed: onSaveTask
);
  }
}
