// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > taskTile

import 'package:flutter/material.dart';

class TaskTile extends StatelessWidget {
  const TaskTile({super.key, required this.taskTitle, required this.index, required this.taskCheckbox});
  final String taskTitle;
  final int index;
  final Widget taskCheckbox;

  @override
  Widget build(BuildContext context) {
    return ListTile(
    key: Key('taskTile_$index'),
    title: Text(taskTitle),
    leading: taskCheckbox
);
  }
}
