// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > homePage

import 'package:flutter/material.dart';
import '../widgets/counter_button.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key, required this.counterValue, this.counterButtonOnPressed});
  final String counterValue;
  final VoidCallback? counterButtonOnPressed;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
    key: const Key('homePage'),
    body: Center(child: Column(children: [
        Text(counterValue),
        CounterButton(onPressed: counterButtonOnPressed)
    ])),
    appBar: AppBar(title: const Text('Counter App'))
);
  }
}
