// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > homePage

import 'package:flutter/material.dart';
import '../widgets/decrement_button.dart';
import '../widgets/increment_button.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key, required this.counterValue, this.decrementButtonOnPressed, this.incrementButtonOnPressed});
  final String counterValue;
  final VoidCallback? decrementButtonOnPressed;
  final VoidCallback? incrementButtonOnPressed;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
    key: const Key('homePage'),
    body: Center(child: Column(children: [
        Text(counterValue),
        IncrementButton(onPressed: incrementButtonOnPressed),
        DecrementButton(onPressed: decrementButtonOnPressed)
    ])),
    appBar: AppBar(title: const Text('Counter App'))
);
  }
}
