package behaviorflutter

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pietroid/metacode/engine/internal/core/model"
	"github.com/pietroid/metacode/engine/internal/core/plan"
	"github.com/pietroid/metacode/engine/internal/core/run"
	"github.com/pietroid/metacode/engine/internal/llm"
	"github.com/pietroid/metacode/engine/internal/log"
	dataflutter "github.com/pietroid/metacode/engine/internal/specs/data/codegen/flutter"
	projectflutter "github.com/pietroid/metacode/engine/internal/specs/project/codegen/flutter"
	"github.com/pietroid/metacode/engine/internal/specs/ui/catalog"
	uiflutter "github.com/pietroid/metacode/engine/internal/specs/ui/codegen/flutter"
)

type recordingClient struct {
	calls     []llm.Call
	responses []string
}

func (c *recordingClient) Complete(_ context.Context, call llm.Call) (string, error) {
	c.calls = append(c.calls, call)
	if len(c.responses) == 0 {
		return "", nil
	}
	resp := c.responses[0]
	if len(c.responses) > 1 {
		c.responses = c.responses[1:]
	}
	return resp, nil
}

var _ llm.Client = (*recordingClient)(nil)

// scaffold runs the deterministic part of the pipeline into a temp dir, which
// is the state the implementer is handed in a real run.
func scaffold(t *testing.T) (*model.App, plan.Work, string) {
	t.Helper()

	app := counterAppTwoButtons(t)
	dir := t.TempDir()

	for _, generate := range []func(*model.App, string) error{
		projectflutter.Generate,
		dataflutter.Generate,
		func(a *model.App, d string) error { return uiflutter.Generate(a, catalog.Default(), d) },
	} {
		if err := generate(app, dir); err != nil {
			t.Fatalf("scaffold: %v", err)
		}
	}
	work, err := plan.Build(app)
	if err != nil {
		t.Fatalf("plan: %v", err)
	}
	if err := GenerateWrappers(app, work, dir); err != nil {
		t.Fatalf("generate wrappers: %v", err)
	}
	if err := GenerateTests(app, work, dir); err != nil {
		t.Fatalf("generate tests: %v", err)
	}
	return app, work, dir
}

func newImplementer(t *testing.T, client llm.Client) (*Implementer, string) {
	t.Helper()
	app, plan, dir := scaffold(t)
	return New(client, log.Nop(), app, plan, dir), dir
}

// TestImplementMakesExactlyOneCall is the point of this package. The engine
// used to make a request per wrapper and then a request per failing test per
// candidate file; a two-scenario app is now one request, and a seven-scenario
// one is still one request.
func TestImplementMakesExactlyOneCall(t *testing.T) {
	client := &recordingClient{responses: []string{fixtureReply()}}
	impl, _ := newImplementer(t, client)

	if err := impl.Implement(context.Background()); err != nil {
		t.Fatalf("implement: %v", err)
	}
	if len(client.calls) != 1 {
		t.Fatalf("expected exactly 1 llm call, got %d", len(client.calls))
	}
	if client.calls[0].Label != "implement" {
		t.Errorf("expected the call to be labelled for the trace, got %q", client.calls[0].Label)
	}
}

// TestPromptCarriesTheWholeProblem covers the reason the counter Cubit came
// back with placeholder bodies: the request that wrote it had never been shown
// the scenarios or the tests it had to satisfy.
func TestPromptCarriesTheWholeProblem(t *testing.T) {
	client := &recordingClient{responses: []string{fixtureReply()}}
	impl, _ := newImplementer(t, client)

	if err := impl.Implement(context.Background()); err != nil {
		t.Fatalf("implement: %v", err)
	}
	prompt := client.calls[0].Prompt

	for _, want := range []string{
		// Every scenario, by name and by clause, not just the one a task named.
		"Scenario: increments from 0",
		"Scenario: not decrements when is 0",
		"Then: counterStore.value should be 1",
		// The resolved bindings, so the model calls the Cubit rather than emit.
		"incrementButton.onPressed -> counterStore.increment",
		"decrementButton.onPressed -> counterStore.decrement",
		// Every test, because they are the definition of done.
		"testWidgets(",
		"find.byKey(const Key('incrementButton'))",
		// The code it must write against and the code it must write.
		"class CounterState",
		"class HomePage",
		"lib/stores/counter_cubit.dart",
		"lib/wrappers/home_page_wrapper.dart",
	} {
		if !strings.Contains(prompt, want) {
			t.Errorf("expected the prompt to contain %q", want)
		}
	}
}

func TestImplementWritesEveryFileTheReplyCarries(t *testing.T) {
	client := &recordingClient{responses: []string{fixtureReply()}}
	impl, dir := newImplementer(t, client)

	if err := impl.Implement(context.Background()); err != nil {
		t.Fatalf("implement: %v", err)
	}

	cubit := readFile(t, dir, "lib/stores/counter_cubit.dart")
	if !strings.Contains(cubit, "state.value + 1") {
		t.Errorf("expected the cubit body to be written, got:\n%s", cubit)
	}
	if !strings.Contains(cubit, "GENERATED BY METACODE") {
		t.Errorf("expected the generated marker to survive, got:\n%s", cubit)
	}

	wrapper := readFile(t, dir, "lib/wrappers/home_page_wrapper.dart")
	if !strings.Contains(wrapper, "class HomePageWrapper") {
		t.Errorf("expected the wrapper to be written, got:\n%s", wrapper)
	}
}

// TestApplyIgnoresFilesItDoesNotOwn keeps a reply from rewriting a test to
// match the code. A test the model can edit verifies nothing.
func TestApplyIgnoresFilesItDoesNotOwn(t *testing.T) {
	reply := "```dart\n// FILE: test/increments_from_0_test.dart\nclass Nope {}\n```\n" +
		"```dart\n// FILE: lib/widgets/increment_button.dart\nclass Nope {}\n```\n"
	client := &recordingClient{responses: []string{reply}}
	impl, dir := newImplementer(t, client)

	before := readFile(t, dir, "lib/widgets/increment_button.dart")

	err := impl.Implement(context.Background())
	if err == nil {
		t.Fatal("expected an error when a reply writes nothing this stage owns")
	}

	if after := readFile(t, dir, "lib/widgets/increment_button.dart"); after != before {
		t.Error("a generated widget was overwritten by the model")
	}
	if strings.Contains(readFile(t, dir, "test/increments_from_0_test.dart"), "class Nope") {
		t.Error("a generated test was overwritten by the model")
	}
}

// TestRepairSendsOneCallForEveryFailure pins the second half of the saving: a
// fix iteration is one request whatever the failure count.
func TestRepairSendsOneCallForEveryFailure(t *testing.T) {
	client := &recordingClient{responses: []string{fixtureReply()}}
	impl, _ := newImplementer(t, client)

	failures := []run.Failure{
		{File: "test/increments_from_0_test.dart", Name: "increments from 0", Message: "Expected: <1> Actual: <0>"},
		{File: "test/not_decrements_when_is_0_test.dart", Name: "not decrements when is 0", Message: "Expected: <0> Actual: <-1>"},
	}

	if err := impl.Repair(context.Background(), 1, failures); err != nil {
		t.Fatalf("repair: %v", err)
	}
	if len(client.calls) != 1 {
		t.Fatalf("expected 1 llm call for 2 failures, got %d", len(client.calls))
	}

	prompt := client.calls[0].Prompt
	for _, want := range []string{
		"Expected: <1> Actual: <0>",
		"Expected: <0> Actual: <-1>",
		"not decrements when is 0",
	} {
		if !strings.Contains(prompt, want) {
			t.Errorf("expected the repair prompt to contain %q", want)
		}
	}
	if client.calls[0].Label != "repair 1" {
		t.Errorf("expected the iteration in the call label, got %q", client.calls[0].Label)
	}
}

func readFile(t *testing.T, dir, rel string) string {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(dir, rel))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(content)
}

func fixtureReply() string {
	return strings.Join([]string{
		"Here are the files.",
		"```dart",
		"// FILE: lib/stores/counter_cubit.dart",
		"import 'package:flutter_bloc/flutter_bloc.dart';",
		"import 'counter_state.dart';",
		"",
		"class CounterCubit extends Cubit<CounterState> {",
		"  CounterCubit() : super(const CounterState(value: 0));",
		"  void increment() => emit(CounterState(value: state.value + 1));",
		"  void decrement() {",
		"    if (state.value <= 0) return;",
		"    emit(CounterState(value: state.value - 1));",
		"  }",
		"}",
		"```",
		"```dart",
		"// FILE: lib/wrappers/home_page_wrapper.dart",
		"import 'package:flutter/material.dart';",
		"",
		"class HomePageWrapper extends StatelessWidget {",
		"  const HomePageWrapper({super.key});",
		"  @override",
		"  Widget build(BuildContext context) => const Placeholder();",
		"}",
		"```",
	}, "\n")
}
