// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: data.yaml > taskStore
//
// The class, its state, and the method signatures come from the specs. Method
// bodies are business logic: they are filled in from the behavior scenarios by
// the implement stage, and re-scaffolded on the next run.

import 'package:flutter_bloc/flutter_bloc.dart';
import 'task_state.dart';
import '../models/task.dart';

class TaskCubit extends Cubit<TaskState> {
  TaskCubit() : super(const TaskState(value: []));

  /// Starts from a state a caller chooses, which is how a generated test sets
  /// up a scenario's "Given" without reaching into the store.
  TaskCubit.seeded(TaskState initial) : super(initial);

  /// Specified by:
  ///   adding/adding a second task appends it to the list with counter: given taskStore.value: [{"description":"Buy milk","done":false}], then taskStore.value.first.description should be New task 2
  ///   adding/adding a task appends it to the list: given taskStore.value: [], then taskStore.value.first.description should be New task
  void addTask() {
    final count = state.value.length;
    final description = count == 0 ? 'New task' : 'New task ${count + 1}';
    final newTask = Task(description: description, done: false);
    emit(state.copyWith(value: [newTask, ...state.value]));
  }

  /// Specified by:
  ///   toggling/toggling a row leaves the other rows alone: given taskStore.value: [{"description":"Buy milk","done":false},{"description":"Call mom","done":false}], then taskStore.value.first.done should be false
  ///   toggling/toggling a row marks its task done: given taskStore.value: [{"description":"Buy milk","done":false}], then taskStore.value.first.done should be true
  ///   toggling/toggling a row twice returns it to open: given taskStore.value: [{"description":"Buy milk","done":true}], then taskStore.value.first.done should be false
  void taskToggled(int index) {
    final updated = [
      for (var i = 0; i < state.value.length; i++)
        if (i == index)
          Task(
            description: state.value[i].description,
            done: !state.value[i].done,
          )
        else
          state.value[i],
    ];
    emit(state.copyWith(value: updated));
  }
}