// GENERATED BY METACODE - SCAFFOLDING ONLY
// Source spec: data.yaml > taskStore
//
// The class, its state, and the method signatures come from the specs. Method
// bodies are business logic: they are filled in from the behavior scenarios by
// the implement stage, and re-scaffolded on the next run.

import 'package:flutter_bloc/flutter_bloc.dart';
import '../models/task.dart';
import 'task_state.dart';

class TaskCubit extends Cubit<TaskState> {
  TaskCubit() : super(const TaskState(value: []));

  /// Starts from a state a caller chooses, which is how a generated test sets
  /// up a scenario's "Given" without reaching into the store.
  TaskCubit.seeded(TaskState initial) : super(initial);

  /// Specified by:
  ///   adding/adding a second task appends it to the list with counter: given taskStore.value: [{"description":"Buy milk","done":false}], then taskStore.value.first.description should be New task 2
  ///   adding/adding a task appends it to the list: given taskStore.value: [], then taskStore.value.first.description should be New task
  void addTask() {
    final count = state.value.length + 1;
    final description = count == 1 ? 'New task' : 'New task $count';
    final newTask = Task(description: description, done: false);
    emit(state.copyWith(value: [newTask, ...state.value]));
  }

  /// Specified by:
  ///   toggling/toggling a row leaves the other rows alone: given taskStore.value: [{"description":"Buy milk","done":false},{"description":"Call mom","done":false}], then taskStore.value.first.done should be false
  ///   toggling/toggling a row marks its task done: given taskStore.value: [{"description":"Buy milk","done":false}], then taskStore.value.first.done should be true
  ///   toggling/toggling a row twice returns it to open: given taskStore.value: [{"description":"Buy milk","done":true}], then taskStore.value.first.done should be false
  void taskToggled(int index) {
    final tasks = List<Task>.from(state.value);
    final task = tasks[index];
    tasks[index] = Task(description: task.description, done: !task.done);
    emit(state.copyWith(value: tasks));
  }

}