// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/counter_cubit.dart';

class CounterButtonWrapper extends StatelessWidget {
  const CounterButtonWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: () => context.read<CounterCubit>().increment(),
      child: const Text('Increment'),
    );
  }
}
