// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/counter_cubit.dart';
import '../widgets/decrement_button.dart';

class DecrementButtonWrapper extends StatelessWidget {
  const DecrementButtonWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return DecrementButton(
      onPressed: () => context.read<CounterCubit>().decrement(),
    );
  }
}