// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../pages/home_page.dart';
import '../stores/counter_cubit.dart';
import '../stores/counter_state.dart';

class HomePageWrapper extends StatelessWidget {
  const HomePageWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocSelector<CounterCubit, CounterState, String>(
      selector: (state) => state.value.toString(),
      builder: (context, value) => HomePage(
        counterValue: value,
        decrementButtonOnPressed: () => context.read<CounterCubit>().decrement(),
        incrementButtonOnPressed: () => context.read<CounterCubit>().increment(),
      ),
    );
  }
}