// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/counter_cubit.dart';
import '../stores/counter_state.dart';
import 'counter_button_wrapper.dart';

class HomePageWrapper extends StatelessWidget {
  const HomePageWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter App')),
      body: Center(
        child: Column(
          children: [
    BlocSelector<CounterCubit, CounterState, String>(
      selector: (state) => state.value.toString(),
      builder: (context, counterValue) => Text(counterValue),
    ),
    CounterButtonWrapper()
          ],
        ),
      ),
    );
  }
}
