// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Wires HomePage to CounterCubit.

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../pages/home_page.dart';
import '../stores/counter_cubit.dart';
import '../stores/counter_state.dart';

class HomePageWrapper extends StatelessWidget {
  const HomePageWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocSelector<CounterCubit, CounterState, int>(
      selector: (state) => state.value,
      builder: (context, value) {
        return HomePage(
          counterValue: '$value',
          incrementButtonOnPressed: () =>
              context.read<CounterCubit>().increment(),
          decrementButtonOnPressed: () =>
              context.read<CounterCubit>().decrement(),
        );
      },
    );
  }
}