// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Wires IncrementButton to CounterCubit.

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../stores/counter_cubit.dart';
import '../widgets/increment_button.dart';

class IncrementButtonWrapper extends StatelessWidget {
  const IncrementButtonWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return IncrementButton(
      key: const Key('incrementButton'),
      onPressed: () => context.read<CounterCubit>().increment(),
    );
  }
}