// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > defaultState

import 'package:flutter/material.dart';

class DefaultState extends StatelessWidget {
  const DefaultState({super.key, required this.taskList, required this.taskTile});
  final List<dynamic> taskList;
  final Widget Function(BuildContext, int) taskTile;

  @override
  Widget build(BuildContext context) {
    return Column(
    key: const Key('defaultState'),
    children: [
        Text('Minhas tarefas'),
        Expanded(child: ListView.builder(
        itemCount: taskList.length,
        itemBuilder: taskTile
        ))
    ]
);
  }
}
