// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > emptyState

import 'package:flutter/material.dart';

class EmptyState extends StatelessWidget {
  const EmptyState({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
    key: const Key('emptyState'),
    child: Text('Bla')
);
  }
}
