// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > taskCheckbox

import 'package:flutter/material.dart';

class TaskCheckbox extends StatelessWidget {
  const TaskCheckbox({super.key, this.taskToggled, required this.taskDone, required this.index});
  final ValueChanged<bool?>? taskToggled;
  final bool taskDone;
  final int index;

  @override
  Widget build(BuildContext context) {
    return Checkbox(
    key: Key('taskCheckbox_$index'),
    value: taskDone,
    onChanged: taskToggled
);
  }
}
