// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > adding/saving closes the sheet

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sheet_app/stores/task_cubit.dart';
import 'package:sheet_app/stores/task_state.dart';
import 'package:sheet_app/navigation/router.dart';
import 'support/navigation_spy.dart';

void main() {
  testWidgets('saving closes the sheet', (tester) async {
    final cubit = TaskCubit();
    final navigation = NavigationSpy();
    final router = buildRouter(observers: [navigation]);
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: MaterialApp.router(routerConfig: router),
      ),
    );
    await tester.pumpAndSettle();
    // The scenario starts on this route, so the test goes there the way a
    // user would. Getting there is setup, not behavior, so the recorder is
    // emptied before the scenario begins.
    router.pushNamed('addTask');
    await tester.pumpAndSettle();
    navigation.clear();
    await tester.tap(find.byKey(const Key('saveTaskButton')));
    await tester.pumpAndSettle();
    expect(navigation.popped.length, 1);
  });
}
