// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > adding/pressing add opens the sheet

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sheet_app/stores/task_cubit.dart';
import 'package:sheet_app/stores/task_state.dart';
import 'package:sheet_app/navigation/router.dart';
import 'support/navigation_spy.dart';

void main() {
  testWidgets('pressing add opens the sheet', (tester) async {
    final cubit = TaskCubit();
    final navigation = NavigationSpy();
    final router = buildRouter(observers: [navigation]);
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: MaterialApp.router(routerConfig: router),
      ),
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const Key('addTaskButton')));
    await tester.pumpAndSettle();
    expect(navigation.pushed.where((route) => route == 'addTask').length, 1);
  });
}
