// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > homeState/show empty state when taskStore is empty

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sheet_app/stores/task_cubit.dart';
import 'package:sheet_app/stores/task_state.dart';
import 'package:sheet_app/navigation/router.dart';
import 'support/navigation_spy.dart';
import 'package:sheet_app/models/task.dart';

void main() {
  testWidgets('show empty state when taskStore is empty', (tester) async {
    final cubit = TaskCubit.seeded(TaskState(value: []));
    final navigation = NavigationSpy();
    final router = buildRouter(observers: [navigation]);
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: MaterialApp.router(routerConfig: router),
      ),
    );
    await tester.pumpAndSettle();
    
    expect(find.byKey(const Key('emptyState')), findsOneWidget);
  });
}
