// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > toggling/toggling a row marks its task done

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sheet_app/stores/task_cubit.dart';
import 'package:sheet_app/stores/task_state.dart';
import 'package:sheet_app/navigation/router.dart';
import 'support/navigation_spy.dart';
import 'package:sheet_app/models/task.dart';

void main() {
  testWidgets('toggling a row marks its task done', (tester) async {
    final cubit = TaskCubit.seeded(TaskState(value: [Task(description: 'Buy milk', done: false)]));
    final navigation = NavigationSpy();
    final router = buildRouter(observers: [navigation]);
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: MaterialApp.router(routerConfig: router),
      ),
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const Key('taskCheckbox_0')));
    await tester.pump();
    expect(cubit.state.value.first.done, true);
  });
}
