// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > counterButton

import 'package:flutter/material.dart';

class CounterButton extends StatelessWidget {
  const CounterButton({super.key});

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
    key: const Key('counterButton'),
    child: const Text('Increment'),
    onPressed: null
);
  }
}
