// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > decrementButton

import 'package:flutter/material.dart';

class DecrementButton extends StatelessWidget {
  const DecrementButton({super.key, this.onPressed});
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
    key: const Key('decrementButton'),
    child: const Text('Decrement'),
    onPressed: onPressed
);
  }
}
