// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > incrementButton

import 'package:flutter/material.dart';

class IncrementButton extends StatelessWidget {
  const IncrementButton({super.key, this.onPressed});
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
    key: const Key('incrementButton'),
    child: const Text('Increment'),
    onPressed: onPressed
);
  }
}
