// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > counterStore/increments from 1

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:counter_app/stores/counter_cubit.dart';
import 'package:counter_app/stores/counter_state.dart';
import 'package:counter_app/wrappers/home_page_wrapper.dart';

void main() {
  testWidgets('increments from 1', (tester) async {
    final cubit = CounterCubit();
    cubit.emit(CounterState(value: 1));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    await tester.tap(find.byType(ElevatedButton));
    await tester.pump();
    expect(cubit.state.value, 2);
  });
}
