// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > decrements from 2

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:counter_app/stores/counter_cubit.dart';
import 'package:counter_app/stores/counter_state.dart';
import 'package:counter_app/wrappers/home_page_wrapper.dart';

void main() {
  testWidgets('decrements from 2', (tester) async {
    final cubit = CounterCubit();
    cubit.emit(CounterState(value: 2));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    await tester.tap(find.byKey(const Key('decrementButton')));
    await tester.pump();
    expect(cubit.state.value, 1);
  });
}
