// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > Show counter value on the home page

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:counter_app/stores/counter_cubit.dart';
import 'package:counter_app/stores/counter_state.dart';
import 'package:counter_app/wrappers/home_page_wrapper.dart';

void main() {
  testWidgets('Show counter value on the home page', (tester) async {
    final cubit = CounterCubit();
    cubit.emit(CounterState(value: 5));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    
    expect(find.text('5'), findsOneWidget);
  });
}
