package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Marker is the first line of every file this engine generates. Pruning uses it
// to tell its own output from anything a person put in the same directory.
const Marker = "GENERATED BY METACODE"

// markerScanLimit is how far into a file the marker is looked for. It sits in
// the header comment, so a short prefix is enough.
const markerScanLimit = 512

// Prune deletes generated files under the given directories that the current
// run did not produce. Paths in expected are relative to root, slash-separated.
//
// Generation only ever wrote files, so renaming a widget or a scenario left the
// old output on disk. Stale test files kept running and kept failing, which is
// how one renamed widget turned into a list of failures for scenarios that no
// longer existed.
//
// A file is removed only if it carries Marker, so hand-written files in the same
// directory survive.
func Prune(root string, dirs []string, expected map[string]bool) ([]string, error) {
	var removed []string

	for _, dir := range dirs {
		abs := filepath.Join(root, filepath.FromSlash(dir))
		entries, err := os.ReadDir(abs)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read %s: %w", dir, err)
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			rel := dir + "/" + entry.Name()
			if expected[rel] {
				continue
			}
			path := filepath.Join(abs, entry.Name())
			generated, err := isGenerated(path)
			if err != nil {
				return nil, err
			}
			if !generated {
				continue
			}
			if err := os.Remove(path); err != nil {
				return nil, fmt.Errorf("remove %s: %w", rel, err)
			}
			removed = append(removed, rel)
		}
	}

	sort.Strings(removed)
	return removed, nil
}

func isGenerated(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	buf := make([]byte, markerScanLimit)
	n, err := f.Read(buf)
	if err != nil && n == 0 {
		// An empty or unreadable file is not something this engine wrote.
		return false, nil
	}
	return strings.Contains(string(buf[:n]), Marker), nil
}
