// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: navigation.yaml

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'stores/task_cubit.dart';
import 'navigation/router.dart';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // Static, so the widget stays const-constructible and the router is built
  // once. A GoRouter holds the navigation stack, so building one per rebuild
  // would reset it.
  static final _router = buildRouter();

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => TaskCubit(),
      child: MaterialApp.router(

              title: 'sheet_app',
              routerConfig: _router,
            
      ),
    );
  }
}
