// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > adding/adding a task appends it to the list

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:focus_app/stores/task_cubit.dart';
import 'package:focus_app/stores/task_state.dart';
import 'package:focus_app/wrappers/home_page_wrapper.dart';
import 'package:focus_app/models/task.dart';

void main() {
  testWidgets('adding a task appends it to the list', (tester) async {
    final cubit = TaskCubit.seeded(TaskState(value: []));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    await tester.tap(find.byKey(const Key('addTaskButton')));
    await tester.pump();
    expect(cubit.state.value.first.description, 'New task');
  });
}
