// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > homeState/show empty state when taskStore is empty

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:focus_app/stores/task_cubit.dart';
import 'package:focus_app/stores/task_state.dart';
import 'package:focus_app/wrappers/home_page_wrapper.dart';
import 'package:focus_app/models/task.dart';

void main() {
  testWidgets('show empty state when taskStore is empty', (tester) async {
    final cubit = TaskCubit.seeded(TaskState(value: []));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    
    expect(find.byKey(const Key('emptyState')), findsOneWidget);
  });
}
