// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > rendering/render a checkbox reflecting the task it belongs to

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:focus_app/stores/task_cubit.dart';
import 'package:focus_app/stores/task_state.dart';
import 'package:focus_app/wrappers/home_page_wrapper.dart';
import 'package:focus_app/models/task.dart';

void main() {
  testWidgets('render a checkbox reflecting the task it belongs to', (tester) async {
    final cubit = TaskCubit.seeded(TaskState(value: [Task(description: 'Buy milk', done: false), Task(description: 'Call mom', done: true)]));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    
    expect(tester.widget<Checkbox>(find.byKey(const Key('taskCheckbox_1'))).value, true);
  });
}
