// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > rendering/render each row with its own task

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:focus_app/stores/task_cubit.dart';
import 'package:focus_app/stores/task_state.dart';
import 'package:focus_app/wrappers/home_page_wrapper.dart';
import 'package:focus_app/models/task.dart';

void main() {
  testWidgets('render each row with its own task', (tester) async {
    final cubit = TaskCubit.seeded(TaskState(value: [Task(description: 'Buy milk', done: false), Task(description: 'Call mom', done: false)]));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    
    expect(find.descendant(of: find.byKey(const Key('taskTile_1')), matching: find.text('Call mom')), findsOneWidget);
  });
}
