// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: behaviors.yaml > toggling/toggling a row twice returns it to open

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:focus_app/stores/task_cubit.dart';
import 'package:focus_app/stores/task_state.dart';
import 'package:focus_app/wrappers/home_page_wrapper.dart';
import 'package:focus_app/models/task.dart';

void main() {
  testWidgets('toggling a row twice returns it to open', (tester) async {
    final cubit = TaskCubit.seeded(TaskState(value: [Task(description: 'Buy milk', done: true)]));
    await tester.pumpWidget(
      BlocProvider.value(
        value: cubit,
        child: const MaterialApp(home: HomePageWrapper()),
      ),
    );
    await tester.tap(find.byKey(const Key('taskCheckbox_0')));
    await tester.pump();
    expect(cubit.state.value.first.done, false);
  });
}
