// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > homePage

import 'package:flutter/material.dart';
import 'pages/home_page.dart';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'counter_app',
      home: const HomePage(counterValue: ''),
    );
  }
}
