package dart

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"metacode/internal/graph"
	"metacode/internal/spec"
	"metacode/internal/utils"
)

// Generate writes the generated Flutter project into outDir.
func Generate(p *graph.Project, outDir string) error {
	files, err := GenerateFiles(p)
	if err != nil {
		return err
	}
	for relPath, content := range files {
		fullPath := filepath.Join(outDir, relPath)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return fmt.Errorf("creating dir for %s: %w", relPath, err)
		}
		if err := os.WriteFile(fullPath, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", relPath, err)
		}
	}
	return nil
}

// GenerateFiles returns a map of relative file path to file contents.
func GenerateFiles(p *graph.Project) (map[string]string, error) {
	files := map[string]string{}

	files["pubspec.yaml"] = generatePubspec(p)
	files["lib/main.dart"] = generateMain(p)

	for _, store := range sortedStores(p.Stores) {
		rel := fmt.Sprintf("lib/models/%s.dart", utils.ToSnakeCase(store.Name))
		files[rel] = generateStore(p, store)
	}

	for _, widget := range sortedWidgets(p.Widgets) {
		rel := fmt.Sprintf("lib/pages/%s.dart", utils.ToSnakeCase(widget.Name))
		files[rel] = generateWidget(p, widget)
	}

	tests, err := generateTests(p)
	if err != nil {
		return nil, err
	}
	files["test/metacode_test.dart"] = tests

	return files, nil
}

func generatePubspec(p *graph.Project) string {
	return `name: counter_example
description: Generated by Metacode
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
`
}

func generateMain(p *graph.Project) string {
	// Use the first page-like UI widget as the home page.
	homeName := ""
	for _, w := range sortedWidgets(p.Widgets) {
		if w.Root.Kind != "button" {
			homeName = w.Name
			break
		}
	}

	b := strings.Builder{}
	b.WriteString("import 'package:flutter/material.dart';\n")
	for _, store := range sortedStores(p.Stores) {
		b.WriteString(fmt.Sprintf("import 'models/%s.dart';\n", utils.ToSnakeCase(store.Name)))
	}
	if homeName != "" {
		b.WriteString(fmt.Sprintf("import 'pages/%s.dart';\n", utils.ToSnakeCase(homeName)))
	}

	home := "Container()"
	if homeName != "" {
		args := widgetConstructorArgsInline(p)
		if args != "" {
			home = fmt.Sprintf("%s(\n        %s\n      )", utils.ToUpperCamel(homeName), strings.ReplaceAll(args, "\n", "\n        "))
		} else {
			home = fmt.Sprintf("%s()", utils.ToUpperCamel(homeName))
		}
	}

	b.WriteString("\nvoid main() {\n  runApp(const MyApp());\n}\n\n")
	b.WriteString("class MyApp extends StatelessWidget {\n")
	b.WriteString("  const MyApp({super.key});\n\n")
	b.WriteString("  @override\n")
	b.WriteString("  Widget build(BuildContext context) {\n")
	b.WriteString("    return MaterialApp(\n")
	b.WriteString("      title: 'Counter Example',\n")
	b.WriteString(fmt.Sprintf("      home: %s,\n", home))
	b.WriteString("    );\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}

func generateStore(p *graph.Project, store *graph.Store) string {
	className := utils.ToUpperCamel(store.Name)
	b := strings.Builder{}
	b.WriteString("import 'package:flutter/foundation.dart';\n\n")
	b.WriteString(fmt.Sprintf("class %s extends ChangeNotifier {\n", className))

	for _, field := range store.Fields {
		dartType := dartType(field.Type)
		b.WriteString(fmt.Sprintf("  %s _%s;\n", dartType, field.Name))
	}

	b.WriteString("\n  " + className + "({")
	params := []string{}
	for _, field := range store.Fields {
		dartType := dartType(field.Type)
		if field.InitialValue != "" {
			params = append(params, fmt.Sprintf("%s %s = %s", dartType, field.Name, field.InitialValue))
		} else {
			params = append(params, fmt.Sprintf("required %s %s", dartType, field.Name))
		}
	}
	b.WriteString(strings.Join(params, ", "))
	b.WriteString("}) : ")
	initList := []string{}
	for _, field := range store.Fields {
		initList = append(initList, fmt.Sprintf("_%s = %s", field.Name, field.Name))
	}
	b.WriteString(strings.Join(initList, ", "))
	b.WriteString(";\n\n")

	for _, field := range store.Fields {
		dartType := dartType(field.Type)
		b.WriteString(fmt.Sprintf("  %s get %s => _%s;\n", dartType, field.Name, field.Name))
		b.WriteString(fmt.Sprintf("  set %s(%s value) {\n", field.Name, dartType))
		b.WriteString(fmt.Sprintf("    _%s = value;\n", field.Name))
		b.WriteString("    notifyListeners();\n")
		b.WriteString("  }\n\n")
	}

	for method := range p.StoreMethods(store.Name) {
		b.WriteString(generateStoreMethod(store, method))
	}

	b.WriteString("}\n")
	return b.String()
}

func generateStoreMethod(store *graph.Store, method string) string {
	field := findIntField(store)
	switch method {
	case "increment":
		if field == nil {
			return fmt.Sprintf("  void increment() { /* no integer field to increment */ }\n\n")
		}
		return fmt.Sprintf("  void increment() {\n    _%s++;\n    notifyListeners();\n  }\n\n", field.Name)
	case "decrement":
		if field == nil {
			return fmt.Sprintf("  void decrement() { /* no integer field to decrement */ }\n\n")
		}
		return fmt.Sprintf("  void decrement() {\n    _%s--;\n    notifyListeners();\n  }\n\n", field.Name)
	default:
		return fmt.Sprintf("  void %s() {\n    throw UnimplementedError('%s() is not implemented yet');\n  }\n\n", method, method)
	}
}

func findIntField(store *graph.Store) *spec.DataField {
	for _, f := range store.Fields {
		if f.Type == "int" {
			return &f
		}
	}
	return nil
}

func generateWidget(p *graph.Project, widget *graph.Widget) string {
	className := utils.ToUpperCamel(widget.Name)
	b := strings.Builder{}
	b.WriteString("import 'package:flutter/material.dart';\n")
	for _, store := range sortedStores(p.Stores) {
		b.WriteString(fmt.Sprintf("import '../models/%s.dart';\n", utils.ToSnakeCase(store.Name)))
	}
	refs := collectWidgetRefs(widget.Root)
	for _, name := range sortedWidgetNames(refs) {
		if name == widget.Name {
			continue
		}
		b.WriteString(fmt.Sprintf("import '../pages/%s.dart';\n", utils.ToSnakeCase(name)))
	}
	b.WriteString("\n")

	b.WriteString(fmt.Sprintf("class %s extends StatelessWidget {\n", className))
	for _, store := range sortedStores(p.Stores) {
		b.WriteString(fmt.Sprintf("  final %s %s;\n", utils.ToUpperCamel(store.Name), utils.ToLowerCamel(store.Name)))
	}
	b.WriteString("\n  const " + className + "({super.key")
	for _, store := range sortedStores(p.Stores) {
		b.WriteString(fmt.Sprintf(", required this.%s", utils.ToLowerCamel(store.Name)))
	}
	b.WriteString("});\n\n")

	b.WriteString("  @override\n")
	b.WriteString("  Widget build(BuildContext context) {\n")

	body := renderNode(p, widget.Name, widget.Root, 2)
	if widget.Root.Kind == "button" {
		b.WriteString("    return " + strings.ReplaceAll(body, "\n", "\n    ") + ";\n")
	} else {
		b.WriteString("    return Scaffold(\n")
		b.WriteString("      body: " + indentBlock(body, 6) + ",\n")
		b.WriteString("    );\n")
	}

	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String()
}

func renderNode(p *graph.Project, widgetName string, node spec.WidgetNode, baseIndent int) string {
	prefix := strings.Repeat(" ", baseIndent)
	inner := strings.Repeat(" ", baseIndent+2)

	switch node.Kind {
	case "stack":
		b := strings.Builder{}
		b.WriteString(prefix + "Stack(\n")
		b.WriteString(prefix + "  children: [\n")
		for _, child := range node.Children {
			b.WriteString(renderNode(p, widgetName, child, baseIndent+4))
			b.WriteString(",\n")
		}
		b.WriteString(prefix + "  ],\n")
		b.WriteString(prefix + ")")
		return b.String()

	case "center":
		if len(node.Children) != 1 {
			return prefix + "Center(child: Container())"
		}
		child := renderNode(p, widgetName, node.Children[0], baseIndent+2)
		return prefix + "Center(\n" + inner + "child: " + child + ",\n" + prefix + ")"

	case "align", "aligned":
		alignment := "center"
		if a, ok := node.Props["alignment"].(string); ok {
			alignment = a
		}
		if len(node.Children) != 1 {
			return prefix + "Align(alignment: Alignment." + alignment + ", child: Container())"
		}
		child := renderNode(p, widgetName, node.Children[0], baseIndent+2)
		return prefix + "Align(\n" + inner + "alignment: Alignment." + alignment + ",\n" + inner + "child: " + child + ",\n" + prefix + ")"

	case "text":
		if binding, ok := p.TextBindings[node.Content]; ok {
			storeVar := utils.ToLowerCamel(binding.StoreName)
			return prefix + "ListenableBuilder(\n" +
				inner + "listenable: " + storeVar + ",\n" +
				inner + "builder: (context, child) => Text(\n" +
				inner + "  '${" + storeVar + "." + binding.FieldName + "}',\n" +
				inner + "  key: const Key('" + binding.DisplayKey + "'),\n" +
				inner + "),\n" +
				prefix + ")"
		}
		return prefix + "Text('" + node.Content + "')"

	case "button":
		label := "Button"
		if l, ok := node.Props["label"].(string); ok {
			label = l
		}
		onPressed := "null"
		if action, ok := p.ButtonActions[widgetName]; ok {
			onPressed = action
		}
		return prefix + "FloatingActionButton(\n" +
			inner + "onPressed: " + onPressed + ",\n" +
			inner + "child: const Text('" + label + "'),\n" +
			prefix + ")"

	case "reference":
		return renderReference(p, node.Content, baseIndent)
	}

	return prefix + "Container()"
}

func renderReference(p *graph.Project, name string, baseIndent int) string {
	prefix := strings.Repeat(" ", baseIndent)
	inner := strings.Repeat(" ", baseIndent+2)
	className := utils.ToUpperCamel(name)
	args := widgetConstructorArgs(p)
	if args != "" {
		args = ",\n" + inner + args
	}
	return prefix + className + "(\n" + inner + "key: const Key('" + name + "')" + args + ",\n" + prefix + ")"
}

func widgetConstructorArgs(p *graph.Project) string {
	parts := []string{}
	for _, store := range sortedStores(p.Stores) {
		parts = append(parts, fmt.Sprintf("%s: %s", utils.ToLowerCamel(store.Name), utils.ToLowerCamel(store.Name)))
	}
	return strings.Join(parts, ",\n")
}

func generateTests(p *graph.Project) (string, error) {
	b := strings.Builder{}
	b.WriteString("import 'package:flutter/material.dart';\n")
	b.WriteString("import 'package:flutter_test/flutter_test.dart';\n")
	for _, store := range sortedStores(p.Stores) {
		b.WriteString(fmt.Sprintf("import '../lib/models/%s.dart';\n", utils.ToSnakeCase(store.Name)))
	}
	pageRefs := map[string]bool{}
	for _, test := range p.Tests {
		if test.When != nil && p.IsUIPath(test.When.Path) {
			pageRefs[test.When.Path[0]] = true
		}
		for _, then := range test.Then {
			if p.IsUIPath(then.Path) {
				pageRefs[then.Path[0]] = true
			}
		}
	}
	for _, name := range sortedStringKeys(pageRefs) {
		b.WriteString(fmt.Sprintf("import '../lib/pages/%s.dart';\n", utils.ToSnakeCase(name)))
	}
	b.WriteString("\nvoid main() {\n")

	for _, test := range p.Tests {
		body, err := generateTestBody(p, test)
		if err != nil {
			return "", fmt.Errorf("test %q: %w", test.Name, err)
		}
		b.WriteString(body)
	}

	b.WriteString("}\n")
	return b.String(), nil
}

func generateTestBody(p *graph.Project, test *graph.Test) (string, error) {
	isWidget := isWidgetTest(p, test)
	b := strings.Builder{}

	if isWidget {
		b.WriteString(fmt.Sprintf("  testWidgets('%s', (WidgetTester tester) async {\n", escapeDartString(test.Name)))
	} else {
		b.WriteString(fmt.Sprintf("  test('%s', () {\n", escapeDartString(test.Name)))
	}

	// Instantiate every store.
	storeVars := map[string]string{}
	storeInitializers := map[string]map[string]string{}
	for _, store := range sortedStores(p.Stores) {
		storeVars[store.Name] = utils.ToLowerCamel(store.Name)
		storeInitializers[store.Name] = map[string]string{}
	}

	for _, a := range test.Given {
		path := strings.Split(a.Target, ".")
		if !p.IsStorePath(path) {
			continue
		}
		storeName := path[0]
		fieldName := path[len(path)-1]
		storeInitializers[storeName][fieldName] = a.Value
	}

	for _, store := range sortedStores(p.Stores) {
		varName := storeVars[store.Name]
		className := utils.ToUpperCamel(store.Name)
		args := []string{}
		for _, field := range store.Fields {
			if v, ok := storeInitializers[store.Name][field.Name]; ok {
				args = append(args, fmt.Sprintf("%s: %s", field.Name, v))
			}
		}
		if len(args) > 0 {
			b.WriteString(fmt.Sprintf("    final %s = %s(%s);\n", varName, className, strings.Join(args, ", ")))
		} else {
			b.WriteString(fmt.Sprintf("    final %s = %s();\n", varName, className))
		}
	}

	if isWidget {
		homeName := homeWidgetNameForTest(p, test)
		b.WriteString(fmt.Sprintf("    await tester.pumpWidget(MaterialApp(home: %s(%s)));\n", utils.ToUpperCamel(homeName), widgetCallArgs(p, storeVars)))
	}

	if test.When != nil && len(test.When.Path) > 0 {
		whenCode, err := generateWhen(p, test, storeVars)
		if err != nil {
			return "", err
		}
		b.WriteString(whenCode)
	}

	for _, then := range test.Then {
		thenCode, err := generateThen(p, test, then, storeVars)
		if err != nil {
			return "", err
		}
		b.WriteString(thenCode)
	}

	b.WriteString("  });\n\n")
	return b.String(), nil
}

func generateWhen(p *graph.Project, test *graph.Test, storeVars map[string]string) (string, error) {
	when := test.When
	path := when.Path
	if p.IsUIPath(path) && path[len(path)-1] == "onPressed" {
		widgetName := path[len(path)-2]
		b := strings.Builder{}

		// Capture before value for known increment/decrement expectations.
		if hasMethodCallExpectation(test, "increment") || hasMethodCallExpectation(test, "decrement") {
			for _, store := range sortedStores(p.Stores) {
				b.WriteString(fmt.Sprintf("    final %sBefore = %s.value;\n", storeVars[store.Name], storeVars[store.Name]))
			}
		}

		b.WriteString(fmt.Sprintf("    await tester.tap(find.byKey(const Key('%s')));\n", widgetName))
		b.WriteString("    await tester.pump();\n")
		return b.String(), nil
	}

	if p.IsStorePath(path) {
		storeName := path[0]
		method := path[len(path)-1]
		return fmt.Sprintf("    %s.%s();\n", storeVars[storeName], method), nil
	}

	return "", fmt.Errorf("unhandled when clause: %s", when.Raw)
}

// widgetConstructorArgsInline returns constructor arguments with inline store
// instantiation, used in places where there is no local store variable (e.g. main.dart).
func widgetConstructorArgsInline(p *graph.Project) string {
	parts := []string{}
	for _, store := range sortedStores(p.Stores) {
		parts = append(parts, fmt.Sprintf("%s: %s()", utils.ToLowerCamel(store.Name), utils.ToUpperCamel(store.Name)))
	}
	return strings.Join(parts, ",\n")
}

// widgetCallArgs returns constructor arguments for a widget call on a single line.
func widgetCallArgs(p *graph.Project, storeVars map[string]string) string {
	parts := []string{}
	for _, store := range sortedStores(p.Stores) {
		parts = append(parts, fmt.Sprintf("%s: %s", utils.ToLowerCamel(store.Name), storeVars[store.Name]))
	}
	return strings.Join(parts, ", ")
}

func generateThen(p *graph.Project, test *graph.Test, then spec.Action, storeVars map[string]string) (string, error) {
	if then.IsAssignment {
		path := then.Path
		if p.IsStorePath(path) && len(path) >= 2 {
			storeName := path[0]
			fieldName := path[len(path)-1]
			return fmt.Sprintf("    expect(%s.%s, %s);\n", storeVars[storeName], fieldName, then.Value), nil
		}
		if p.IsUIPath(path) {
			return fmt.Sprintf("    expect(find.text('%s'), findsOneWidget);\n", then.Value), nil
		}
		return "", fmt.Errorf("unknown assignment target: %s", then.Target)
	}

	// Method-call expectation (e.g. counterStore.increment after a button tap).
	path := then.Path
	if p.IsStorePath(path) && len(path) >= 2 {
		storeName := path[0]
		method := path[len(path)-1]
		switch method {
		case "increment":
			return fmt.Sprintf("    expect(%s.value, %sBefore + 1);\n", storeVars[storeName], storeVars[storeName]), nil
		case "decrement":
			return fmt.Sprintf("    expect(%s.value, %sBefore - 1);\n", storeVars[storeName], storeVars[storeName]), nil
		default:
			return fmt.Sprintf("    // TODO: assert %s.%s() was called\n", storeVars[storeName], method), nil
		}
	}
	return "", fmt.Errorf("unknown then clause: %s", then.Raw)
}

func hasMethodCallExpectation(test *graph.Test, method string) bool {
	for _, then := range test.Then {
		if then.IsAssignment {
			continue
		}
		if len(then.Path) >= 2 && then.Path[len(then.Path)-1] == method {
			return true
		}
	}
	return false
}

func homeWidgetNameForTest(p *graph.Project, test *graph.Test) string {
	if test.When != nil && p.IsUIPath(test.When.Path) {
		return test.When.Path[0]
	}
	for _, then := range test.Then {
		if p.IsUIPath(then.Path) {
			return then.Path[0]
		}
	}
	if widgets := sortedWidgets(p.Widgets); len(widgets) > 0 {
		return widgets[0].Name
	}
	return "Container"
}

func isWidgetTest(p *graph.Project, test *graph.Test) bool {
	if test.When != nil && p.IsUIPath(test.When.Path) {
		return true
	}
	for _, then := range test.Then {
		if p.IsUIPath(then.Path) {
			return true
		}
	}
	return false
}

func dartType(t string) string {
	switch t {
	case "string":
		return "String"
	case "int":
		return "int"
	case "bool":
		return "bool"
	case "double":
		return "double"
	default:
		return t
	}
}

func sortedStores(stores map[string]*graph.Store) []*graph.Store {
	keys := make([]string, 0, len(stores))
	for k := range stores {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := make([]*graph.Store, len(keys))
	for i, k := range keys {
		out[i] = stores[k]
	}
	return out
}

func sortedWidgets(widgets map[string]*graph.Widget) []*graph.Widget {
	keys := make([]string, 0, len(widgets))
	for k := range widgets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := make([]*graph.Widget, len(keys))
	for i, k := range keys {
		out[i] = widgets[k]
	}
	return out
}

func collectWidgetRefs(node spec.WidgetNode) map[string]bool {
	refs := map[string]bool{}
	var walk func(spec.WidgetNode)
	walk = func(n spec.WidgetNode) {
		if n.Kind == "reference" && n.Content != "" {
			refs[n.Content] = true
		}
		for _, c := range n.Children {
			walk(c)
		}
	}
	walk(node)
	return refs
}

func sortedWidgetNames(refs map[string]bool) []string {
	return sortedStringKeys(refs)
}

func sortedStringKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func escapeDartString(s string) string {
	return strings.ReplaceAll(s, "'", "\\'")
}

func indentBlock(s string, indent int) string {
	prefix := strings.Repeat(" ", indent)
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line == "" {
			continue
		}
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}
