// GENERATED BY METACODE - DO NOT EDIT BY HAND
// Source spec: ui.yaml > homePage

import 'package:flutter/material.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key, required this.homeContent, required this.addTaskButton});
  final Widget homeContent;
  final Widget addTaskButton;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
    key: const Key('homePage'),
    body: homeContent,
    floatingActionButton: addTaskButton
);
  }
}
