package flutter

import (
	"context"
	"fmt"
	"strings"

	"github.com/pietroid/metacode/engine/internal/core/ir"
	"github.com/pietroid/metacode/engine/internal/core/order"
	"github.com/pietroid/metacode/engine/internal/modules/data"
	"github.com/pietroid/metacode/engine/internal/modules/shared"
	"github.com/pietroid/metacode/engine/internal/modules/ui/catalog"
	"github.com/pietroid/metacode/engine/internal/planner"
)

// DeterministicGenerator renders wrapper bodies from the IR alone, with no LLM.
// It handles the patterns the catalog can describe: a page laying out its
// children, a button whose press calls a Cubit action, and a text bound to a
// store field via BlocSelector.
type DeterministicGenerator struct{}

// NewDeterministicGenerator returns a Generator that needs no LLM.
func NewDeterministicGenerator() *DeterministicGenerator {
	return &DeterministicGenerator{}
}

// Name implements Generator.
func (g *DeterministicGenerator) Name() string { return "deterministic" }

// Generate implements Generator.
func (g *DeterministicGenerator) Generate(ctx context.Context, app *ir.IR, tasks []planner.Task, outDir string) error {
	return generate(ctx, app, tasks, outDir, g.body)
}

func (g *DeterministicGenerator) body(_ context.Context, app *ir.IR, plan Plan, plans []Plan, _ string) (string, error) {
	comp := shared.FindComponent(app.UI, plan.WidgetName)
	if comp == nil {
		return "", fmt.Errorf("widget %q not found in UI spec", plan.WidgetName)
	}

	store := app.Stores[0]
	c := catalog.New()

	switch {
	case shared.IsPageName(plan.WidgetName):
		return generatePageWrapper(plan, *comp, app, childWrapperClasses(plans), store, c)
	case isButtonKind(comp.Kind):
		return generateButtonWrapper(plan, *comp, app, store)
	default:
		return generateFallbackWrapper(plan)
	}
}

// widgetNameForWrapperTask reads the widget off the task. The planner records
// it there because a task ID is a slug: recovering "homePage" from
// "wrapper-home-page-counter-value" is guesswork that got the casing wrong and
// then failed every symbol lookup that used the result.
func widgetNameForWrapperTask(task planner.Task, _ *ir.IR) string {
	return task.Widget
}

func isButtonKind(kind string) bool {
	switch kind {
	case "elevatedButton", "textButton", "iconButton", "floatingActionButton":
		return true
	}
	return false
}

func generatePageWrapper(plan Plan, comp ir.UIComponent, app *ir.IR, childWrappers map[string]string, store ir.Store, c *catalog.Catalog) (string, error) {
	base := shared.StoreBaseName(store.Name)
	bindings := inferVariableBindings(app, plan.WidgetName, store)

	title := ""
	if appBarRaw, ok := comp.Props["appBar"].(map[string]any); ok {
		if t, ok := appBarRaw["title"].(string); ok {
			title = t
		}
	}

	var bodyChildren []string
	bodyRaw, ok := comp.Props["body"].(map[string]any)
	if ok {
		centerRaw, ok := bodyRaw["center"].(map[string]any)
		if ok {
			if columnList, ok := centerRaw["column"].([]any); ok {
				for _, item := range columnList {
					bodyChildren = append(bodyChildren, renderWrapperListItem(item, app, c, bindings, childWrappers, store))
				}
			}
		}
	}

	childrenArg := ""
	if len(bodyChildren) > 0 {
		childrenArg = fmt.Sprintf("children: [\n%s\n          ]", shared.Indent(strings.Join(bodyChildren, ",\n")))
	}

	var imports []string
	imports = append(imports,
		"import 'package:flutter/material.dart';",
		"import 'package:flutter_bloc/flutter_bloc.dart';",
		fmt.Sprintf("import '../stores/%s_cubit.dart';", shared.SnakeCase(base)),
		fmt.Sprintf("import '../stores/%s_state.dart';", shared.SnakeCase(base)),
	)
	for _, childName := range order.Keys(childWrappers) {
		imports = append(imports, fmt.Sprintf("import '%s_wrapper.dart';", shared.SnakeCase(childName)))
	}

	className := plan.ClassName
	return fmt.Sprintf(`// GENERATED BY METACODE - DO NOT EDIT BY HAND
%s

class %s extends StatelessWidget {
  const %s({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text(%s)),
      body: Center(
        child: Column(
          %s,
        ),
      ),
    );
  }
}
`, strings.Join(imports, "\n"), className, className, shared.DartStringLiteral(title), childrenArg), nil
}

// generateButtonWrapper wraps the generated dumb button, passing the Cubit
// action through the callback parameter the dumb widget exposes. It does not
// re-render the button: the UI module already knows how to do that, and a
// wrapper that rebuilt it would drift from the widget it wraps.
func generateButtonWrapper(plan Plan, comp ir.UIComponent, app *ir.IR, store ir.Store) (string, error) {
	base := shared.StoreBaseName(store.Name)
	cubitClass := shared.PascalCase(base) + "Cubit"
	method, err := storeActionFor(comp.Name, app, store)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf(`// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../stores/%s_cubit.dart';
import '../widgets/%s.dart';

class %s extends StatelessWidget {
  const %s({super.key});

  @override
  Widget build(BuildContext context) {
    return %s(
      onPressed: () => context.read<%s>().%s(),
    );
  }
}
`, shared.SnakeCase(base), shared.SnakeCase(comp.Name),
		plan.ClassName, plan.ClassName,
		shared.PascalCase(comp.Name), cubitClass, method), nil
}

func generateFallbackWrapper(plan Plan) (string, error) {
	className := plan.ClassName
	return fmt.Sprintf(`// GENERATED BY METACODE - DO NOT EDIT BY HAND
import 'package:flutter/material.dart';

class %s extends StatelessWidget {
  const %s({super.key});

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
`, className, className), nil
}

func renderWrapperListItem(raw any, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	switch v := raw.(type) {
	case string:
		if wrapperClass, ok := childWrappers[v]; ok {
			return wrapperClass + "()"
		}
		if sym, ok := app.Symbols.Lookup(v); ok && sym.Kind == "widget" {
			return fmt.Sprintf("const %s()", shared.PascalCase(v))
		}
		return fmt.Sprintf("const Text(%s)", shared.DartStringLiteral(v))
	case map[string]any:
		if len(v) == 1 {
			for _, k := range order.Keys(v) {
				val := v[k]
				if k == "text" {
					if s, ok := val.(string); ok {
						if expr, ok := bindings[s]; ok {
							base := shared.StoreBaseName(store.Name)
							cubitClass := shared.PascalCase(base) + "Cubit"
							stateClass := shared.PascalCase(base) + "State"
							return fmt.Sprintf("BlocSelector<%s, %s, String>(\n  selector: (state) => %s,\n  builder: (context, %s) => Text(%s),\n)", cubitClass, stateClass, expr, s, s)
						}
						return fmt.Sprintf("const Text(%s)", shared.DartStringLiteral(s))
					}
				}
				if c.IsKnown(k) {
					comp := rawMapToComponent(v, k, c)
					return renderWrapperComponent(comp, app, c, bindings, childWrappers, store)
				}
				if wrapperClass, ok := childWrappers[k]; ok {
					return wrapperClass + "()"
				}
				return fmt.Sprintf("const %s()", shared.PascalCase(k))
			}
		}
	}
	return "const SizedBox()"
}

func renderWrapperComponent(comp ir.UIComponent, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	if sym, ok := c.Find(comp.Kind); ok {
		return renderWrapperCatalogWidget(comp, sym, app, c, bindings, childWrappers, store)
	}
	if wrapperClass, ok := childWrappers[comp.Name]; ok {
		return wrapperClass + "()"
	}
	return fmt.Sprintf("const %s()", shared.PascalCase(comp.Name))
}

func renderWrapperCatalogWidget(comp ir.UIComponent, sym catalog.Symbol, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	var args []string
	if sym.DefaultProp != "" {
		if arg := renderWrapperDefaultProp(comp, sym, app, c, bindings, childWrappers, store); arg != "" {
			args = append(args, arg)
		}
	}
	for _, prop := range order.Keys(comp.Props) {
		if prop == sym.DefaultProp {
			continue
		}
		expectsWidget := c.WidgetProp(comp.Kind, prop)
		args = append(args, fmt.Sprintf("%s: %s", prop, renderWrapperPropValue(comp.Props[prop], expectsWidget, app, c, bindings, childWrappers, store)))
	}
	if len(args) == 0 {
		return sym.FlutterWidget + "()"
	}
	return fmt.Sprintf("%s(\n%s\n)", sym.FlutterWidget, shared.Indent(strings.Join(args, ",\n")))
}

func renderWrapperDefaultProp(comp ir.UIComponent, sym catalog.Symbol, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	prop := sym.DefaultProp
	switch prop {
	case catalog.PropChild:
		if len(comp.Children) > 0 {
			return fmt.Sprintf("child: %s", renderWrapperComponent(comp.Children[0], app, c, bindings, childWrappers, store))
		}
		if val, ok := comp.Props[prop]; ok {
			return fmt.Sprintf("child: %s", renderWrapperPropValue(val, true, app, c, bindings, childWrappers, store))
		}
	case catalog.PropChildren:
		if len(comp.Children) > 0 {
			return fmt.Sprintf("children: %s", renderWrapperChildrenList(comp.Children, app, c, bindings, childWrappers, store))
		}
		if list, ok := comp.Props[prop].([]any); ok {
			return fmt.Sprintf("children: %s", renderWrapperRawList(list, true, app, c, bindings, childWrappers, store))
		}
	case catalog.PropTitle, catalog.PropData:
		if val, ok := comp.Props[prop].(string); ok {
			if prop == catalog.PropData {
				if _, bound := bindings[val]; bound {
					return ""
				}
			}
			return fmt.Sprintf("%s: const Text(%s)", prop, shared.DartStringLiteral(val))
		}
	default:
		if val, ok := comp.Props[prop]; ok {
			return fmt.Sprintf("%s: %s", prop, renderWrapperPropValue(val, false, app, c, bindings, childWrappers, store))
		}
	}
	return ""
}

func renderWrapperPropValue(val any, expectsWidget bool, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	switch v := val.(type) {
	case string:
		if expectsWidget {
			if shared.IsVariableIdentifier(v) && !c.IsKnown(v) {
				return fmt.Sprintf("Text(%s)", v)
			}
			return fmt.Sprintf("const Text(%s)", shared.DartStringLiteral(v))
		}
		if shared.IsVariableIdentifier(v) && !c.IsKnown(v) {
			return v
		}
		return shared.DartStringLiteral(v)
	case map[string]any:
		if expectsWidget {
			comp := rawMapToComponent(v, "", c)
			return renderWrapperComponent(comp, app, c, bindings, childWrappers, store)
		}
		return "Container()"
	case []any:
		return renderWrapperRawList(v, expectsWidget, app, c, bindings, childWrappers, store)
	default:
		return fmt.Sprintf("%v", v)
	}
}

func renderWrapperRawList(list []any, expectsWidget bool, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	var parts []string
	for _, item := range list {
		parts = append(parts, renderWrapperListItem(item, app, c, bindings, childWrappers, store))
	}
	return fmt.Sprintf("[\n%s\n]", shared.Indent(strings.Join(parts, ",\n")))
}

func renderWrapperChildrenList(children []ir.UIComponent, app *ir.IR, c *catalog.Catalog, bindings map[string]string, childWrappers map[string]string, store ir.Store) string {
	var parts []string
	for _, child := range children {
		parts = append(parts, renderWrapperComponent(child, app, c, bindings, childWrappers, store))
	}
	return fmt.Sprintf("[\n%s\n]", shared.Indent(strings.Join(parts, ",\n")))
}

func rawMapToComponent(m map[string]any, parentName string, c *catalog.Catalog) ir.UIComponent {
	if len(m) == 1 {
		for _, k := range order.Keys(m) {
			val := m[k]
			if c.IsKnown(k) {
				comp := buildWrapperComponentValue(val, k, c)
				comp.Name = k
				comp.Kind = k
				return comp
			}
			return ir.UIComponent{Name: k, Kind: "widget"}
		}
	}
	return ir.UIComponent{Name: parentName, Kind: parentName, Props: m}
}

func buildWrapperComponentValue(raw any, name string, c *catalog.Catalog) ir.UIComponent {
	comp := ir.UIComponent{Name: name, Kind: name, Props: make(map[string]any)}
	switch v := raw.(type) {
	case map[string]any:
		comp.Props = v
	case string:
		if sym, ok := c.Find(name); ok {
			comp.Props[sym.DefaultProp] = v
		}
	case []any:
		if sym, ok := c.Find(name); ok && sym.DefaultProp == catalog.PropChildren {
			comp.Props[sym.DefaultProp] = v
		}
	}
	return comp
}

func inferVariableBindings(app *ir.IR, pageName string, store ir.Store) map[string]string {
	bindings := make(map[string]string)
	storeNames := map[string]bool{store.Name: true, shared.StoreBaseName(store.Name): true}
	for _, b := range app.Behaviors {
		if b.Then == nil || b.Given == nil {
			continue
		}
		if !strings.HasPrefix(b.Then.Target, pageName+".") {
			continue
		}
		varName := strings.TrimPrefix(b.Then.Target, pageName+".")
		root, field := data.SplitDot(b.Given.Target)
		if !storeNames[root] || field == "" {
			continue
		}
		if b.Then.Value == b.Given.Value {
			bindings[varName] = fmt.Sprintf("state.%s.toString()", field)
		}
	}
	return bindings
}

// storeActionFor returns the store action a button press runs. The link is
// resolved once in the IR, so the wrapper, the store generator, and the test
// generator all agree. It used to be guessed here by parsing the scenario's
// given and then values as integers and comparing them, which named every
// button on a non-numeric store "increment".
func storeActionFor(widgetName string, app *ir.IR, store ir.Store) (string, error) {
	binding, ok := app.Symbols.BindingFor(widgetName, "onPressed")
	if !ok {
		return "", fmt.Errorf("no behavior binds %s.onPressed to a store action", widgetName)
	}
	if binding.Store != store.Name {
		return "", fmt.Errorf("%s.onPressed drives store %q, not %q", widgetName, binding.Store, store.Name)
	}
	return binding.Action, nil
}
