package flutter

import (
	"context"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/pietroid/metacode/engine/internal/planner"
)

// generateWith runs one strategy over the counter app and returns the wrapper
// files it produced, relative to the project, with the class each declares.
func generateWith(t *testing.T, gen Generator) map[string][]string {
	t.Helper()

	app := counterAppFullIR()
	dir := setupGeneratedFiles(t, app)

	tasks, err := planner.Plan(app)
	if err != nil {
		t.Fatalf("plan failed: %v", err)
	}
	if err := gen.Generate(context.Background(), app, tasks, dir); err != nil {
		t.Fatalf("%s generate failed: %v", gen.Name(), err)
	}

	return wrapperClasses(t, dir)
}

var anyClassDecl = regexp.MustCompile(`class\s+(\w+)\b`)

func wrapperClasses(t *testing.T, dir string) map[string][]string {
	t.Helper()

	out := make(map[string][]string)
	root := filepath.Join(dir, "lib", "wrappers")
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		var classes []string
		for _, m := range anyClassDecl.FindAllStringSubmatch(string(content), -1) {
			classes = append(classes, m[1])
		}
		sort.Strings(classes)
		out[filepath.ToSlash(rel)] = classes
		return nil
	})
	if err != nil {
		t.Fatalf("walk %s: %v", root, err)
	}
	return out
}

// TestStrategiesAgreeOnFilesAndClassNames is the contract that makes the
// counter app a valid example either way: whichever strategy runs, the
// generated project has the same wrapper files declaring the same classes.
// Only the bodies differ.
func TestStrategiesAgreeOnFilesAndClassNames(t *testing.T) {
	deterministic := generateWith(t, NewDeterministicGenerator())
	ai := generateWith(t, NewLLMGenerator(&mockClient{}))

	if len(deterministic) == 0 {
		t.Fatal("deterministic strategy generated no wrappers")
	}

	for _, file := range sortedKeys(deterministic) {
		aiClasses, ok := ai[file]
		if !ok {
			t.Errorf("%s: generated by deterministic strategy but not by ai", file)
			continue
		}
		if strings.Join(aiClasses, ",") != strings.Join(deterministic[file], ",") {
			t.Errorf("%s: classes differ, deterministic=%v ai=%v", file, deterministic[file], aiClasses)
		}
	}
	for _, file := range sortedKeys(ai) {
		if _, ok := deterministic[file]; !ok {
			t.Errorf("%s: generated by ai strategy but not by deterministic", file)
		}
	}
}

// TestLLMStrategyEnforcesClassName covers the case the mock cannot: a model
// that returns a class named something other than what was asked for.
func TestLLMStrategyEnforcesClassName(t *testing.T) {
	app := counterAppFullIR()
	dir := setupGeneratedFiles(t, app)

	tasks, err := planner.Plan(app)
	if err != nil {
		t.Fatalf("plan failed: %v", err)
	}

	mock := &mockClient{
		response: "```dart\nclass Whatever extends StatelessWidget {\n  const Whatever({super.key});\n  @override\n  Widget build(BuildContext context) => const Whatever2();\n}\n```",
	}
	if err := NewLLMGenerator(mock).Generate(context.Background(), app, tasks, dir); err != nil {
		t.Fatalf("generate wrappers failed: %v", err)
	}

	code, err := os.ReadFile(filepath.Join(dir, "lib", "wrappers", "home_page_wrapper.dart"))
	if err != nil {
		t.Fatalf("read wrapper: %v", err)
	}
	if !strings.Contains(string(code), "class HomePageWrapper extends StatelessWidget") {
		t.Errorf("expected the wrapper class to be renamed to HomePageWrapper, got:\n%s", code)
	}
	if strings.Contains(string(code), "class Whatever ") {
		t.Errorf("expected the model's class name to be replaced, got:\n%s", code)
	}
	// Whatever2 is a different identifier and must survive untouched.
	if !strings.Contains(string(code), "Whatever2()") {
		t.Errorf("expected unrelated identifiers to survive the rename, got:\n%s", code)
	}
}

func sortedKeys(m map[string][]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
